language: go

go:
  - 1.6

#before_cache:

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v ./...

script:
  - git log --oneline | head -n 1
  - go test -coverprofile=../coverage.txt -covermode=atomic
  - rm -rf $GOPATH/src/github.com/gurupras/phonelab_backend/
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
