language: go

go:
  - 1.6

#before_cache:
#  - rm -rf $GOPATH/src/github.com/gurupras/phonelab_backend

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v ./...

script:
  - git log --oneline | head -n 1
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
