language: go

go:
  - 1.6

#before_cache:

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v -u ./...

script:
  - git log --oneline | head -n 1
  - mkdir $HOME/copy
  - rsync -azpr ./ $HOME/copy/
  - go test -coverprofile=$HOME/copy/coverage.txt -covermode=atomic -timeout=30s -v
  - rm -rf $GOPATH/src/github.com/gurupras/phonelab_backend
  - cd $HOME/copy

after_success:
  - bash <(curl -s https://codecov.io/bash)
